server:

  port: 8980

  servlet:
    context-path: /

spring:
  mvc:
    static-path-pattern: /static/**

  datasource:
    url: jdbc:log4jdbc:mysql://192.168.6.42:3306/dotsite?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: dotsite
    password: 123456
    driver-class-name: net.sf.log4jdbc.DriverSpy

  thymeleaf:
    cache: false
    check-template: false
    check-template-location: false
